var positive = [["active","characterized by energetic movement"],
    ["adaptable","capable of fitting a particular situation or use"],
    ["admirable","inspiring approval"],
    ["adventurous","willing to undertake new and daring enterprises"],
    ["agree","consent or assent to a condition"],
    ["alert","warn or arouse to a sense of danger"],
    ["amiable","diffusing warmth and friendliness"],
    ["anticipative","marked by eager anticipation"],
    ["appreciative","having or showing a favorable critical judgment or opinion"],
    ["articulate","express or state clearly"],
    ["aspiring","desiring or striving for recognition or advancement"],
    ["athletic","relating to sports"],
    ["attractive","pleasing to the eye or mind as through beauty or charm"],
    ["balanced","being in a state of proper equilibrium"],
    ["benevolent","showing or motivated by sympathy and understanding"],
    ["brilliant","full of light; shining intensely"],
    ["calm","not agitated; without losing self-possession"],
    ["capable","having ability"],
    ["captivating","capturing interest as if by a spell"],
    ["caring","feeling and exhibiting concern and empathy for others"],
    ["challenging","requiring full use of your abilities or resources"],
    ["charismatic","possessing an extraordinary ability to attract"],
    ["charming","pleasing or delighting"],
    ["cheerful","being full of or promoting cheer"],
    ["clean","tidy, organized, straight-edge"],
    ["clever","mentally quick and resourceful"],
    ["colorful","unusual, eccentric"],
    ["compassionate","showing or having sympathy for another's suffering"],
    ["conciliatory","making or willing to make concessions"],
    ["confident","having or marked by assurance"],
    ["conscientious","characterized by extreme care and great effort"],
    ["considerate","showing concern for the rights and feelings of others"],
    ["constant","uninterrupted in time and indefinitely long continuing"],
    ["contemplative","deeply or seriously thoughtful"],
    ["cooperative","involving the joint activity of two or more"],
    ["courageous","able to face and deal with danger or fear without flinching"],
    ["courteous","characterized by politeness and gracious good manners"],
    ["creative","having the ability or power to invent or make something"],
    ["cultured","marked by refinement in taste and manners"],
    ["curious","eager to investigate and learn or learn more"],
    ["daring","a challenge to do something dangerous or foolhardy"],
    ["debonair","having a sophisticated charm"],
    ["decent","socially or conventionally correct; refined or virtuous"],
    ["decisive","characterized by resoluteness and firmness"],
    ["dedicated","devoted to a cause or ideal or purpose"],
    ["deep","having great spatial extension downward or inward"],
    ["dignified","formal or stately in bearing or appearance"],
    ["directed","(often used in combination) having a specified direction"],
    ["disciplined","exhibiting self-control and obeying the rules"],
    ["discreet","marked by prudence or modesty and wise self-restraint"],
    ["dramatic","characteristic of a stage performance"],
    ["dutiful","willingly obedient out of a sense of respect"],
    ["dynamic","characterized by action or forcefulness of personality"],
    ["earnest","characterized by a firm, humorless belief in one's opinions"],
    ["ebullient","joyously unrestrained"],
    ["educate","give knowledge acquired by learning and instruction"],
    ["efficient","being effective without wasting time, effort, or expense"],
    ["elegant","refined and tasteful in appearance, behavior, or style"],
    ["eloquent","expressing yourself readily, clearly, effectively"],
    ["empathetic","showing ready comprehension of others' states"],
    ["energetic","possessing or displaying forceful exertion"],
    ["enthusiastic","having or showing great excitement and interest"],
    ["esthetic","concerning an appreciation of beauty or good taste"],
    ["exciting","creating or arousing uncontrolled emotion"],
    ["extraordinary","highly unusual or exceptional or remarkable"],
    ["fair","free from favoritism, bias, or deception"],
    ["faithful","loyal and reliable"],
    ["farsighted","able to see distant objects clearly"],
    ["firm","not soft or yielding to pressure"],
    ["flexible","able to bend easily"],
    ["focused","brought into sharp clarity"],
    ["forceful","characterized by power or strength"],
    ["forgiving","inclined or able to forgive and show mercy"],
    ["forthright","directly and without evasion; not roundabout"],
    ["freethinking","the doctrine that reason is the right basis for regulating conduct"],
    ["friendly","characteristic of or befitting an ally"],
    ["gallant","having or displaying great dignity or nobility"],
    ["generous","willing to give and share unstintingly"],
    ["gentle","soft and mild; not harsh or stern or severe"],
    ["genuine","not fake or counterfeit"],
    ["good-natured","having an easygoing and cheerful disposition"],
    ["gracious","characterized by kindness and warm courtesy"],
    ["hardworking","characterized by hard work and perseverance"],
    ["healthy","free from infirmity or disease"],
    ["hearty","showing warm and sincere friendliness"],
    ["helpful","providing assistance or serving a useful function"],
    ["high-minded","of high moral or intellectual value"],
    ["honest","marked by truth"],
    ["honorable","deserving of esteem and respect"],
    ["humble","marked by meekness or modesty; not arrogant or prideful"],
    ["humorous","characterized by the power to evoke laughter"],
    ["idealistic","of high moral or intellectual value"],
    ["imaginative","marked by independence and creativity in thought or action"],
    ["impressive","making a strong or vivid mental image"],
    ["incisive","demonstrating ability to recognize or draw fine distinctions"],
    ["incorruptible","incapable of being morally corrupted"],
    ["independent","free from external control and constraint"],
    ["individualistic","marked by or expressing a distinct personality"],
    ["innovative","being like nothing done or experienced or created before"],
    ["inoffensive","giving no offense"],
    ["insightful","exhibiting clear and deep perception"],
    ["insouciant","marked by unconcern"],
    ["intelligent","having the capacity for thought and reason to a high degree"],
    ["intuitive","spontaneously derived from or prompted by a natural tendency"],
    ["invulnerable","immune to attack; impregnable"],
    ["kind","having a tender and considerate and helpful nature"],
    ["knowledge","the result of perception, learning, and reasoning"],
    ["leisurely","not hurried or forced"],
    ["liberal","showing or characterized by broad-mindedness"],
    ["logical","based on known statements or events or conditions"],
    ["lovable","having characteristics that attract love or affection"],
    ["loyal","steadfast in allegiance or duty"],
    ["lyrical","expressing deep emotion"],
    ["magnanimous","noble and generous in spirit"],
    ["many-sided","having many parts or sides"],
    ["mature","having reached full natural growth or development"],
    ["methodical","characterized by orderliness"],
    ["moderate","marked by avoidance of extravagance or extremes"],
    ["modest","marked by simplicity; having a humble opinion of yourself"],
    ["neat","clean or organized"],
    ["objective","the goal intended to be attained"],
    ["observant","quick to notice; showing quick and keen perception"],
    ["open","affording free passage or access"],
    ["optimistic","hopeful that the best will happen in the future"],
    ["orderly","clean or organized"],
    ["organized","methodical and efficient in arrangement or function"],
    ["original","preceding all others in time"],
    ["painstaking","characterized by extreme care and great effort"],
    ["passionate","having or expressing strong emotions"],
    ["patient","enduring trying circumstances with even temper"],
    ["patriotic","inspired by love for your country"],
    ["peaceful","not disturbed by strife or turmoil or war"],
    ["perceptive","of or relating to awareness via the senses"],
    ["perfectionist","one displeased by anything that does not meet high standards"],
    ["personable","pleasant in manner and appearance"],
    ["persuasive","intended or having the power to induce action or belief"],
    ["playful","full of fun and high spirits"],
    ["polished","perfected or made shiny and smooth"],
    ["popular","regarded with great favor or approval by the general public"],
    ["practical","guided by experience and observation rather than theory"],
    ["precise","sharply exact or accurate or delimited"],
    ["principled","based on objectively defined standards of rightness"],
    ["profound","situated at or extending to great depth"],
    ["protean","taking on different forms"],
    ["protective","intended or adapted to provide safety of some kind"],
    ["providential","peculiarly fortunate or appropriate"],
    ["prudent","marked by sound judgment"],
    ["punctual","acting or arriving exactly at the time appointed"],
    ["rational","consistent with or based on or using reason"],
    ["realistic","aware or expressing awareness of things as they are"],
    ["reflective","capable of physically throwing back light or sound"],
    ["relaxed","without strain or anxiety"],
    ["reliable","worthy of trust"],
    ["resourceful","adroit or imaginative"],
    ["respectful","exhibiting an attitude of admiration or esteem"],
    ["responsible","worthy of or requiring trust; held accountable"],
    ["responsive","reacting to a stimulus"],
    ["reverential","feeling or manifesting veneration"],
    ["romantic","expressive of or exciting love"],
    ["rustic","characteristic of rural life"],
    ["sage","a mentor in spiritual and philosophical topics"],
    ["sane","mentally healthy; free from mental disorder"],
    ["scholarly","characteristic of a learned person"],
    ["scrupulous","characterized by extreme care and great effort"],
    ["secure","free from danger or risk"],
    ["selfless","showing concern for the welfare of others"],
    ["self-denying","willing to deprive yourself"],
    ["self-reliant","(of persons) free from external control and constraint in e.g. action and judgment"],
    ["sensitive","responsive to physical stimuli"],
    ["sentimental","marked by tender, romantic, or nostalgic emotion"],
    ["seraphic","having a sweet nature befitting an angel"],
    ["serious","of great consequence"],
    ["sexy","marked by or tending to arouse sensual desire or interest"],
    ["sharing","unselfishly willing to partake with others"],
    ["shrewd","marked by practical hardheaded intelligence"],
    ["simple","having few parts; not complex or complicated or involved"],
    ["skillful","having or showing knowledge and skill and aptitude"],
    ["sober","not affected by a chemical substance, especially alcohol"],
    ["sociable","inclined to or conducive to companionship with others"],
    ["solid","not soft or yielding to pressure"],
    ["sophisticated","having worldly knowledge and refinement"],
    ["spontaneous","said or done without having been planned in advance"],
    ["sporting","relating to or used in sports"],
    ["stable","resistant to change of position or condition"],
    ["steadfast","marked by firm determination or resolution; not shakable"],
    ["steady","securely in position; not shaky"],
    ["stoic","seeming unaffected by pleasure or pain; impassive"],
    ["strong","having strength or power greater than average or expected"],
    ["studious","characterized by diligent learning and fondness for reading"],
    ["suave","having a sophisticated charm"],
    ["subtle","difficult to detect or grasp by the mind or analyze"],
    ["Sweet","English phonetician; one of the founders of modern phonetics"],
    ["sympathetic","expressing compassion or friendly fellow feelings"],
    ["systematic","characterized by order and planning"],
    ["tasteful","having or showing or conforming to good taste"],
    ["thorough","painstakingly careful and accurate"],
    ["tidy","marked by order and cleanliness in appearance or habits"],
    ["tolerant","showing or characterized by broad-mindedness"],
    ["tractable","easily managed"],
    ["trusting","inclined to believe or confide readily"],
    ["uncomplaining","not complaining"],
    ["understanding","the condition of someone who knows and comprehends"],
    ["dogmatic","pertaining to a code of beliefs accepted as authoritative"],
    ["upright","in a vertical position; not sloping"],
    ["urbane","showing a high degree of refinement"],
    ["venturesome","disposed to take risks"],
    ["vivacious","vigorous and animated"],
    ["warm","having or producing a comfortable and agreeable degree of heat or imparting or maintaining heat"],
    ["well-bred","of good upbringing"],
    ["well-read","well informed or deeply versed through reading"],
    ["well-rounded","many-sided"],
    ["winning","succeeding with great difficulty"],
    ["wise","having intelligence and discernment"],
    ["witty","combining clever conception and facetious expression"]];


var neutral = [["aggressive","characteristic of an enemy or one eager to fight"],
  ["ambitious","having a strong desire for success or achievement"],
  ["amusing","providing enjoyment; pleasantly entertaining"],
  ["artful","not straightforward or candid"],
  ["ascetic","someone who practices self denial as a spiritual discipline"],
  ["authoritarian","characteristic of an absolute ruler or absolute rule"],
  ["boyish","befitting or characteristic of a young male"],
  ["businesslike","exhibiting methodical and systematic characteristics that would be useful in business"],
  ["busy","actively or fully engaged or occupied"],
  ["casual","without or seeming to be without plan or method; offhand"],
  ["chum","a close friend"],
  ["circumspect","heedful of potential consequences"],
  ["competitive","involving rivalry over something"],
  ["complex","complicated in structure"],
  ["confidential","given in secret"],
  ["conservative","resistant to change"],
  ["contradictory","not able to be true at the same time"],
  ["crisp","tender and brittle"],
  ["cute","attractive especially by means of smallness or prettiness"],
  ["deceptive","designed to mislead either deliberately or inadvertently"],
  ["determined","having been learned or found especially by investigation"],
  ["dominating","offensively self-assured or exercising unwarranted power"],
  ["dream","a series of images and emotions occurring during sleep"],
  ["driven","having a compulsive or urgent quality a driven sense of obligation; propelled or motivated by something"],
  ["droll","comical in an odd or whimsical manner"],
  ["dry","sarcastic, subtle, unemotive"],
  ["effeminate","having unsuitable feminine qualities"],
  ["emotional","of or pertaining to feelings"],
  ["enigmatic","not clear to the understanding"],
  ["experimental","of the nature of or undergoing a trial"],
  ["familial","relating to a social unit living together"],
  ["folksy","very informal and familiar"],
  ["formal","in accord with established conventions and requirements "],
  ["freewheeling","free of restraints or rules"],
  ["frugal","avoiding waste"],
  ["glamorous","having an air of allure, romance and excitement"],
  ["guileless","free of deceit"],
  ["high-spirited","joyously unrestrained"],
  ["hypnotic","of or relating to a state that resembles sleep"],
  ["iconoclastic","characterized by attack on established beliefs"],
  ["idiosyncratic","peculiar to the individual"],
  ["impassive","having or revealing little emotion or sensibility"],
  ["impersonal","not relating to or responsive to individuals"],
  ["impressionable","easily influenced"],
  ["intense","possessing a distinctive feature to a heightened degree"],
  ["invisible","impossible or nearly impossible to see"],
  ["irreligious","hostile or indifferent to religion"],
  ["irreverent","showing lack of due respect or veneration"],
  ["maternal","characteristic of a mother"],
  ["mellow","having a full and pleasing flavor through proper aging"],
  ["modern","ahead of the times"],
  ["moralistic","narrowly and conventionally moral"],
  ["mystical","beyond ordinary understanding"],
  ["neutral","having no personal preference"],
  ["noncommittal","refusing to bind oneself to a particular course of action"],
  ["obedient","dutifully complying with the commands of those in authority"],
  ["old-fashioned","out of fashion"],
  ["ordinary","lacking special distinction, rank, or status"],
  ["outspoken","given to expressing yourself freely or insistently"],
  ["paternalistic","benevolent but sometimes intrusive"],
  ["physical","involving the body as distinguished from the mind or spirit"],
  ["placid","free from disturbance by heavy waves"],
  ["political","involving or characteristic of governing or social power"],
  ["predictable","capable of being foretold"],
  ["preoccupied","having excessive or compulsive concern with something"],
  ["private","confined to particular persons or groups"],
  ["progressive","favoring or promoting progress"],
  ["proud","feeling self-respect, self-esteem, or self-importance"],
  ["pure","free of extraneous elements of any kind"],
  ["questioning","a request for information"],
  ["quiet","characterized by an absence of agitation or activity"],
  ["religious","having or showing belief in and reverence for a deity"],
  ["reserved","set aside for the use of a particular person or party"],
  ["restrained","under control"],
  ["retiring","of a person who has held and relinquished a position"],
  ["sarcastic","expressing or expressive of ridicule that wounds"],
  ["self-conscious","aware of yourself as an individual or of your own being"],
  ["sensual","marked by the appetites and passions of the body"],
  ["skeptical","marked by or given to doubt"],
  ["smooth","having a surface free from roughness or irregularities"],
  ["soft","yielding readily to pressure or weight"],
  ["solemn","dignified and somber in manner or character"],
  ["solitary","not growing or living in groups or colonies"],
  ["stern","of a strict bearing or demeanor; forbidding in aspect"],
  ["stoic","seeming unaffected by pleasure or pain; impassive"],
  ["strict","rigidly accurate; allowing no deviation from a standard"],
  ["stubborn","tenaciously unwilling to yield"],
  ["stylish","having elegance or taste or refinement in manners or dress"],
  ["subjective","taking place within the mind and modified by individual bias"],
  ["surprise","come upon or take unawares"],
  ["tough","substantially made or constructed"],
  ["ceremonious","characterized by pomp and stately display"],
  ["unchanging","showing little if any change"],
  ["undemanding","requiring little if any patience or effort or skill"],
  ["unfathomable","impossible to come to understand"],
  ["unhurried","relaxed and leisurely; without hurry or haste"],
  ["uninhibited","not restrained"],
  ["patriotic","inspired by love for your country"],
  ["sentimental","marked by tender, romantic, or nostalgic emotion"]];


var negative = [["abrupt","exceedingly sudden and unexpected"],
  ["agonize","suffer anguish"],
  ["aimless","drifting without direction"],
  ["airy","open to or abounding in fresh atmosphere"],
  ["aloof","remote in manner"],
  ["moral","concerned with principles of right and wrong"],
  ["angry","feeling or showing extreme displeasure or hostility"],
  ["anxious","causing or fraught with or showing anxiety"],
  ["apathetic","showing little or no emotion or animation"],
  ["arbitrary","based on or subject to individual discretion or preference"],
  ["argumentative","given to or characterized by a tendency to dispute"],
  ["artificial","contrived by art rather than nature"],
  ["asocial","given to avoiding association with others"],
  ["assertive","aggressively self-assured"],
  ["astigmatic","of or relating to a defect in the eye or in a lens caused by a deviation from spherical curvature which prevents light rays from meeting at a common focus and so results in distorted images"],
  ["barbaric","without civilizing influences"],
  ["bewildered","perplexed by many conflicting situations or statements"],
  ["bizarre","conspicuously or grossly unconventional or unusual"],
  ["bland","lacking taste or flavor or tang"],
  ["blunt","not sharp (used of a knife or other blade)"],
  ["boisterous","full of rough and exuberant animal spirits"],
  ["brittle","having little elasticity"],
  ["brutal","resembling a beast; showing lack of human sensibility"],
  ["calculate","make a mathematical computation"],
  ["callous","emotionally hardened"],
  ["careless","marked by lack of attention or consideration or forethought"],
  ["cautious","showing careful forethought"],
  ["childish","indicating a lack of maturity"],
  ["clumsy","lacking grace in movement or posture"],
  ["coarse","rough to the touch"],
  ["cold","having a low or inadequate temperature"],
  ["colorless","weak in color; not colorful"],
  ["complacent","contented to a fault with oneself or one's actions"],
  ["complaintive","expressing pain or dissatisfaction of resentment"],
  ["compulsive","caused by an irrational motive for repetitive actions"],
  ["conceited","having an exaggerated sense of self-importance"],
  ["condemn","express strong disapproval of"],
  ["conformist","someone who follows established standards of conduct "],
  ["confused","unable to think with clarity or act intelligently"],
  ["contemptible","deserving of contempt or scorn"],
  ["conventional","following accepted customs and proprieties"],
  ["cowardly","lacking courage; ignobly timid and faint-hearted"],
  ["crafty","marked by skill in deception"],
  ["crass","so unrefined as to be lacking in discrimination"],
  ["crazy","affected with madness or insanity"],
  ["criminal","someone who has committed a punishable act"],
  ["critical","of a serious examination and judgment of something"],
  ["crude","belonging to an early stage of technical development"],
  ["cruel","able or disposed to inflict pain or suffering"],
  ["cynical","believing the worst of human nature and motives"],
  ["decadent","marked by excessive self-indulgence and moral decay"],
  ["deceitful","marked by deliberate deceptiveness "],
  ["delicate","developed with extreme subtlety"],
  ["demand","request urgently and forcefully"],
  ["dependent","a person who relies on another person for support"],
  ["desperate","a person who is frightened and in need of help"],
  ["destructive","causing damage"],
  ["devious","deviating from a straight course"],
  ["difficult","requiring great physical or mental effort to accomplish"],
  ["dirty","soiled or likely to soil with dirt or grime"],
  ["disconcerting","causing an emotional disturbance"],
  ["discontent","a longing for something better than the present situation"],
  ["discourage","try to prevent; show opposition to"],
  ["courteous","characterized by politeness and gracious good manners"],
  ["dishonest","deceptive or fraudulent"],
  ["loyal","steadfast in allegiance or duty"],
  ["disobedient","unwilling to submit to authority"],
  ["disorderly","lacking any regular or logical organization"],
  ["disorganized","lacking order or methodical arrangement or function"],
  ["disputatious","showing an inclination to disagree"],
  ["disrespectful","exhibiting lack of regard; rude and discourteous"],
  ["disruptive","characterized by unrest or disorder or insubordination"],
  ["dissolute","unrestrained by convention or morality"],
  ["dissonant","harmonically unresolved"],
  ["disturbing","causing distress or worry or anxiety"],
  ["dogmatic","pertaining to a code of beliefs accepted as authoritative"],
  ["domineering","tending to rule in a cruel manner"],
  ["dull","so lacking in interest as to cause mental weariness"],
  ["egocentric","limited to or caring only about yourself and your own needs"],
  ["enervate","weaken mentally or morally"],
  ["envious","painfully desirous of another's advantages"],
  ["erratic","liable to sudden unpredictable change"],
  ["escapist","a person who frequently retreats into a world of fantasy"],
  ["excitable","easily excited"],
  ["expedient","appropriate to a purpose"],
  ["extravagant","recklessly wasteful"],
  ["extreme","of the greatest possible degree, extent, or intensity"],
  ["faithless","having the character of a traitor; disloyal"],
  ["false","not in accordance with the fact or reality or actuality"],
  ["fanatical","marked by excessive enthusiasm for a cause or idea"],
  ["fanciful","indulging in or influenced by the imagination"],
  ["fatalistic","accepting that everything that happens is inevitable"],
  ["fawning","attempting to win favor by flattery"],
  ["fearful","experiencing or showing fear"],
  ["fickle","liable to sudden unpredictable change"],
  ["fiery","like or suggestive of a flame"],
  ["fixed","unmoving"],
  ["flamboyant","tending to attract attention; marked by ostentatious display"],
  ["foolish","lacking good sense or judgment"],
  ["forgetful","(of memory) deficient in retentiveness or range"],
  ["fraudulent","intended to deceive"],
  ["frighten","cause fear in"],
  ["frivolous","not serious in content or attitude or behavior"],
  ["gloomy","depressingly dark"],
  ["grace","elegance and beauty of movement or expression"],
  ["grand","large and impressive in physical size or extent"],
  ["greedy","immoderately desirous of acquiring something"],
  ["grim","harshly uninviting or formidable in manner or appearance"],
  ["gullible","naive and easily deceived or tricked"],
  ["hateful","evoking or deserving hatred"],
  ["haughty","having or showing arrogant superiority"],
  ["hedonistic","devoted to pleasure"],
  ["hesitant","unable to act or decide quickly or firmly"],
  ["hidebound","stubbornly conservative and narrow-minded"],
  ["high-handed","given to haughty disregard of others"],
  ["hostile","characterized by enmity or ill will"],
  ["ignorant","uneducated in general; lacking knowledge or sophistication"],
  ["imitative","marked by or given to imitation"],
  ["impatient","restless or short-tempered under delay or opposition"],
  ["impractical","not workable"],
  ["imprudent","not wise"],
  ["impulsive","without forethought"],
  ["inconsiderate","lacking regard for the rights or feelings of others"],
  ["incurious","showing absence of intellectual inquisitiveness or natural curiosity"],
  ["indecisive","characterized by lack of resoluteness"],
  ["indulgent","given to yielding to the wishes of someone"],
  ["inert","unable to move or resist motion"],
  ["inhibited","held back or restrained or prevented"],
  ["insecure","lacking in safety"],
  ["insensitive","not noticing or caring about the feelings or needs of others"],
  ["insincere","lacking the quality of being open and truthful"],
  ["insult","treat, mention, or speak to rudely"],
  ["intolerant","unwilling to tolerate difference of opinion"],
  ["irascible","quickly aroused to anger"],
  ["irrational","not consistent with or using reason"],
  ["irresponsible","showing lack of care for consequences"],
  ["irritable","easily annoyed"],
  ["lazy","disinclined to work or exertion"],
  ["libidinous","driven by lust"],
  ["loquacious","full of trivial conversation"],
  ["malicious","having the nature of threatening evil"],
  ["mannered","having unnatural behavioral attributes"],
  ["mawkish","effusively or insincerely emotional"],
  ["mealymouthed","hesitant to state facts or opinions simply and directly"],
  ["mechanical","using tools or devices"],
  ["meddlesome","intrusive in an offensive manner"],
  ["melancholic","characterized by or causing or expressing sadness"],
  ["meretricious","tastelessly showy"],
  ["messy","dirty and disorderly"],
  ["miserable","very unhappy"],
  ["miserly","characterized by or indicative of lack of generosity"],
  ["misguided","poorly conceived or thought out"],
  ["mistaken","wrong in opinion or judgment"],
  ["monstrous","distorted and unnatural in shape or size"],
  ["mood","a characteristic state of feeling"],
  ["morbid","suggesting the horror of death and decay"],
  ["naive","marked by or showing unaffected simplicity"],
  ["narcissistic","having an inflated idea of one's own importance"],
  ["narrow","not wide"],
  ["narrow-minded","lacking tolerance or flexibility or breadth of view"],
  ["natty","marked by up-to-dateness in dress and manners"],
  ["neglectful","not showing due care or attention"],
  ["neurotic","affected by worry due to a mental disturbance "],
  ["nihilistic","relating to a complete rejection of moral values and beliefs"],
  ["obnoxious","causing disapproval or protest"],
  ["obsessive","characterized by an unhealthy and compulsive preoccupation"],
  ["obvious","easily perceived by the senses or grasped by the mind"],
  ["odd","not divisible by two"],
  ["offhand","with little or no preparation or forethought"],
  ["one-dimensional","of or in or along or relating to a line"],
  ["one-sided","favoring one person or side over another"],
  ["opinionated","obstinate in your opinions"],
  ["opportunistic","taking advantage of any circumstance of possible benefit"],
  ["oppressed","burdened psychologically or mentally"],
  ["outrageous","greatly exceeding bounds of reason or moderation"],
  ["paranoid","suffering from delusions of persecution or grandeur"],
  ["passive","lacking in energy or will"],
  ["pedantic","marked by a narrow focus on or display of learning"],
  ["perverse","deviating from what is considered moral or right or proper"],
  ["petty","small and of little importance"],
  ["phlegmatic","showing little emotion"],
  ["plod","walk heavily and firmly, as when weary, or through mud"],
  ["pompous","puffed up with vanity"],
  ["possessive","serving to express or indicate the act of having"],
  ["predatory","living by preying on other animals"],
  ["prejudiced","showing bias or bigotry or influenced by preconceived ideas"],
  ["presumptuous","going beyond what is appropriate, permitted, or courteous"],
  ["pretentious","creating an appearance of importance or distinction"],
  ["prim","affectedly dainty or refined"],
  ["procrastinate","postpone doing what one should be doing"],
  ["profligate","unrestrained by convention or morality"],
  ["provocative","serving or tending to excite or stimulate"],
  ["pugnacious","tough and callous by virtue of experience"],
  ["puritanical","of or relating to Puritans or Puritanism"],
  ["quirky","strikingly unconventional"],
  ["reactionary","extremely conservative"],
  ["reactive","participating in processes changing substances into others"],
  ["regimental","belonging to or concerning a regiment"],
  ["regretful","feeling or expressing sorrow or a sense of loss"],
  ["repentant","feeling or expressing remorse for misdeeds"],
  ["repressed","characterized by the suppression of impulses or emotions"],
  ["resentful","full of or marked by indignant ill will"],
  ["ridiculous","incongruous or absurd"],
  ["rigid","incapable of or resistant to bending"],
  ["ritualistic","of or characterized by or adhering to ritualism"],
  ["rowdy","disturbing the public peace; loud and rough"],
  ["ruined","destroyed physically or morally"],
  ["sadistic","deriving pleasure from inflicting pain on another"],
  ["sanctimonious","excessively or hypocritically pious"],
  ["scheming","concealing crafty designs for advancing your own interest"],
  ["scornful","expressing extreme contempt"],
  ["secretive","reluctant to divulge information"],
  ["sedentary","requiring sitting or little activity"],
  ["selfish","concerned chiefly with your own advantage"],
  ["self-indulgent","indulgent of your own appetites and desires"],
  ["shallow","lacking physical depth"],
  ["shortsighted","unable to see distant objects clearly"],
  ["shy","timid and lacking self-confidence"],
  ["silly","ludicrous, foolish"],
  ["single-minded","determined"],
  ["sloppy","lacking neatness or order"],
  ["slow","not moving quickly; taking a comparatively long time"],
  ["sly","marked by skill in deception"],
  ["softheaded","foolish; totally unsound"],
  ["sordid","foul and run-down and repulsive"],
  ["steely","resembling steel in hardness"],
  ["stiff","incapable of or resistant to bending"],
  ["strong-willed","having a determined will"],
  ["stupid","lacking or marked by lack of intellectual acuity"],
  ["submissive","inclined or willing to give in to orders or wishes of others"],
  ["superficial","of, affecting, or being on or near the surface"],
  ["superstitious","showing ignorance of the laws of nature and faith in magic"],
  ["suspicious","openly distrustful and unwilling to confide"],
  ["tactless","lacking what is considerate in dealing with others"],
  ["tasteless","lacking flavor"],
  ["tense","taut or rigid; stretched tight"],
  ["thieve","take unlawfully; steal"],
  ["thought","the content of cognition"],
  ["timid","showing fear and lack of confidence"],
  ["transparent","transmitting light; able to be seen through with clarity"],
  ["treacherous","dangerously unstable and unpredictable"],
  ["trendy","in accord with the latest fad"],
  ["troublesome","difficult to deal with"],
  ["appreciative","having or showing a favorable critical judgment or opinion"],
  ["caring","feeling and exhibiting concern and empathy for others"],
  ["charitable","relating to or characterized by voluntary giving"],
  ["convincing","causing one to believe the truth of something"],
  ["cooperative","involving the joint activity of two or more"],
  ["creative","having the ability or power to invent or make something"],
  ["unctuous","unpleasantly and excessively suave or ingratiating"],
  ["disciplined","exhibiting self-control and obeying the rules"],
  ["unfriendly","not friendly"],
  ["ungrateful","not feeling or showing gratitude"],
  ["healthy","free from infirmity or disease"],
  ["imaginative","marked by independence and creativity in thought or action"],
  ["impressive","making a strong or vivid mental image"],
  ["unlovable","incapable of inspiring love or affection"],
  ["unpolished","not carefully reworked or perfected or made smooth by polishing"],
  ["unprincipled","lacking moral scruples"],
  ["realistic","aware or expressing awareness of things as they are"],
  ["reflective","capable of physically throwing back light or sound"],
  ["unreliable","not worthy of trust"],
  ["unrestrained","not subject to limitation"],
  ["unstable","subject to change; variable"],
  ["vacuous","devoid of matter"],
  ["vague","lacking clarity or distinctness"],
  ["venal","capable of being corrupted"],
  ["venomous","extremely poisonous or injurious"],
  ["vindictive","disposed to seek revenge or intended for revenge"],
  ["vulnerable","capable of being wounded or hurt"],
  ["weak","wanting in physical strength"],
  ["well-meaning","not unfriendly or threatening"],
  ["willful","done by design"],
  ["wishful","having or expressing desire for something"]];
